### PR TITLE
Fix requests console merge skew

### LINKED ISSUE #75237: Run Linters Are Failing On Master
Linters are failing on master and any subsequent PRs, due to something a skew that appears to have occurred between #75164 and #75067: https://github.com/tgstation/tgstation/actions/runs/4908974378/jobs/8765080144#step:7:871

image

```txt
packages/tgui/interfaces/RequestsConsole/MessageWriteTab.tsx(86,13): error TS2322: Type 'unknown[]' is not assignable to type 'string[] | DropdownEntry[]'.
  Type 'unknown[]' is not assignable to type 'string[]'.
    Type 'unknown' is not assignable to type 'string'.
packages/tgui/interfaces/RequestsConsole/MessageWriteTab.tsx(95,13): error TS2322: Type 'unknown[]' is not assignable to type 'string[] | DropdownEntry[]'.
packages/tgui/interfaces/RequestsConsole/MessageWriteTab.tsx(104,13): error TS2322: Type 'unknown[]' is not assignable to type 'string[] | DropdownEntry[]'.
=> Target 'tgui-tsc' failed in 25.915s, exit code: 2
```

Not sure how to fix this because I have skill of noob when it comes to TypeScript stuff like this.

### PR DESCRIPTION
**Pull request by Mothblocks**
- Uses `sortStrings` to avoid downcasting to `unknown[]` (I don't know why this happens)
- Removes `.map(x => x)` because that doesn't do anything (CC @Profakos, don't do this)

Broke with https://github.com/tgstation/tgstation/pull/75164

### CODE REVIEW

**Comment by san7890** [comment]
closes #75237

**Comment by Mothblocks** [comment]
wait for linters this is a web edit

**Comment by SethLafuente** [comment]
that was extremly fast

**Comment by Profakos** [comment]
Well that was silly of me. I am sorry.

**Comment by san7890** [comment]
linters passed

**Comment by jlsnow301** [comment]
> * Uses `sortStrings` to avoid downcasting to `unknown[]` (I don't know why this happens)

The type parameter is in the wrong place. Should be in front of the arrow
